config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users

  root 'tickets#new'

  resources :tickets, only: [:new, :create, :show], constraints: {id: /\d+/}

  scope module: 'admin' do
    resources :tickets, only: [:index, :edit, :update] do
      collection do
        get :search, :filter
      end
    end
    resources :replies, only: :create
    resources :statuses, only: [:new, :create]
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets
  has_many :replies

  def to_s
    email
  end
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :admin_user
  belongs_to :ticket

  validates_presence_of :body
end

app/models/reply_observer.rb
class ReplyObserver < ActiveRecord::Observer
  def after_commit(reply)
    UserMailer.ticket_status(reply.ticket)#.deliver
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  DEFAULT_STATUS = 'Waiting for Staff Response'.freeze
  WAIT_CUSTOMER = 'Waiting for Customer'.freeze
  ON_HOLD = 'On Hold'.freeze
  CANCELED = 'Cancelled'.freeze
  COMPLETED = 'Completed'.freeze

  has_many :tickets

  validates_uniqueness_of :name
  validates_presence_of :name

  scope :ids_by_name, ->(names) { where(name: names).pluck(:id) }

  def self.filter_ids(statuses)
    names = []
    statuses ||= []

    names << Status::DEFAULT_STATUS if statuses.include? '1'
    names << Status::WAIT_CUSTOMER if statuses.include? '2'
    names << Status::ON_HOLD if statuses.include? '3'
    names.concat([Status::CANCELED, Status::COMPLETED]) if statuses.include? '4'

    Status.ids_by_name names
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  has_many :replies
  belongs_to :status
  belongs_to :admin_user

  before_create :set_code, :set_status
  after_save :create_reply_status, if: :status_id_changed?
  after_save :create_reply_admin_user, if: :admin_user_id_changed?

  validates_presence_of :name, :subject, :email, :department, :description
  validates :email, email: true

  scope :find_by_statuses, ->(statuses) { where(status_id: statuses) }

  private

  def set_code
    begin
      self.code = Generator.ticket_random_code
    end while Ticket.exists?(code: code)
  end

  def set_status
    self.status = Status.find_by_name Status::DEFAULT_STATUS
  end

  def create_reply_status
    Reply.create(
      ticket_id: id,
      admin_user_id: 1,
      body: I18n.t('strings.status_changed_reply', status_name: status.name)
    )
  end

  def create_reply_admin_user
    Reply.create(
      ticket_id: id,
      admin_user_id: 1,
      body: I18n.t(
        'strings.admin_user_changed_reply',
        admin_user_email: admin_user.email
      )
    )  
  end
end

app/models/ticket_observer.rb
class TicketObserver < ActiveRecord::Observer
  def after_commit(ticket)
    UserMailer.ticket_status(ticket)#.deliver
  end
end

app/controllers/admin/replies_controller.rb
class Admin::RepliesController < ApplicationController
  before_action :authenticate_admin_user!

  def create
    @reply = Reply.new(reply_params)
    if @reply.save
      flash.notice = I18n.t 'strings.reply_created'
    else
      flash.alert = @reply.errors.full_messages.join(", ")
    end
    redirect_to ticket_path(@reply.ticket)
  end

  private

  def reply_params
    params.require(:reply).permit(:body, :ticket_id, :admin_user_id)
  end
end

app/controllers/admin/statuses_controller.rb
class Admin::StatusesController < ApplicationController
  before_action :authenticate_admin_user!

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      flash.notice = I18n.t 'strings.status_created'
      redirect_to tickets_path
    else
      flash.alert = @status.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def status_params
    params.require(:status).permit(:name)
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < ApplicationController
  before_action :authenticate_admin_user!
  respond_to :html, :json

  def index
    @tickets = Ticket.all
    respond_with(@tickets)
  end

  def search
    @tickets = Ticket.search(params[:query], load: true)
    respond_with(@tickets)
  end

  def filter
    ids = Status.filter_ids(params[:status])
    @tickets = Ticket.find_by_statuses(ids)
    respond_with(@tickets)
  end

  def edit
    @ticket = Ticket.find(params[:id])
    @reply = Reply.new
  end

  def update
    @ticket = Ticket.find(params[:id])
    if @ticket.update(ticket_params)
      flash.notice = I18n.t 'strings.ticket_updated'
      redirect_to ticket_path(@ticket)
    else
      flash.alert = @ticket.errors.full_messages.join(', ')
      render :edit
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:status_id, :admin_user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    tickets_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  respond_to :html, :json

  def new
    @ticket = Ticket.new
  end

  def show
    @ticket = Ticket.find(params[:id])
    respond_with(@ticket)
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      flash.notice = I18n.t 'strings.ticket_created'
      redirect_to ticket_path(@ticket)
    else
      flash.alert = @ticket.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(
      :name, :email, :subject, :description, :department
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/statuses/new.html.haml
.ticket
  =semantic_form_for @status do |f|
    =f.inputs :name
    =f.actions

app/views/admin/tickets/_filters.html.haml
=form_tag search_tickets_path, method: :get do
  %p
    =text_field_tag :query, params[:query]
    =submit_tag 'Search', name: nil

=form_tag filter_tickets_path, method: :get do
  %ol
    %input{ type: 'checkbox', name: 'status[]', value: '1',
      checked: params[:status] && params[:status].include?('1') } 
    =I18n.t 'strings.new_tickets_label'
    %br
    %input{ type: 'checkbox', name: 'status[]', value: '2',
      checked: params[:status] && params[:status].include?('2') }
    =I18n.t 'strings.open_tickets_label'
    %br
    %input{ type: 'checkbox', name: 'status[]', value: '3',
      checked: params[:status] && params[:status].include?('3') }
    =I18n.t 'strings.onhold_tickets_label'
    %br
    %input{ type: 'checkbox', name: 'status[]', value: '4',
      checked: params[:status] && params[:status].include?('4') }
    =I18n.t 'strings.closed_tickets_label'
    %br
    =submit_tag 'Show tickets', name: nil
    %br

app/views/admin/tickets/_reply.html.haml
=semantic_form_for @reply do |f|
  =hidden_field_tag 'reply[ticket_id]', @ticket.id
  =hidden_field_tag 'reply[admin_user_id]', current_admin_user.id
  =f.inputs :body
  =f.actions

app/views/admin/tickets/_table_tickets.html.haml
%table
  %tr
    %th Status
    %th Ticket id
    %th

  -@tickets.each do |ticket|
    %tr
      %td= ticket.status.name
      %td= ticket.code
      %td= link_to 'Show', ticket_path(ticket)
      %td= link_to 'Edit', edit_ticket_path(ticket)

app/views/admin/tickets/edit.html.haml
.ticket
  =semantic_form_for @ticket, url: ticket_path(@ticket), method: :patch do |f|
    =f.inputs :status
    =f.inputs :admin_user
    =f.actions
=render 'reply'

app/views/admin/tickets/filter.html.haml
=render 'filters'
=render 'table_tickets'

app/views/admin/tickets/index.html.haml
=link_to 'Create new status', new_status_path
=render 'filters'
=render 'table_tickets'

app/views/admin/tickets/search.html.haml
=render 'filters'
=render 'table_tickets'

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title IssueTracker
    =stylesheet_link_tag 'application', media: 'all'
    =javascript_include_tag 'application'
    =csrf_meta_tags
  %body
  %nav.navbar.navbar-default.navbar-static-top
    %div.container
      %p
        =link_to 'Main page', root_path
        =link_to 'All tickets', tickets_path
      -if admin_user_signed_in?
        %p.navbar-text Hello, #{current_admin_user.email}
        =link_to button_tag('Sign out', class: 'btn btn-default navbar-btn'),
          destroy_admin_user_session_path, method: :delete
      -else
        =link_to button_tag('Sign in', class: 'btn btn-default navbar-btn'),
          new_admin_user_session_path
        =link_to button_tag('Register', class: 'btn btn-default navbar-btn'), new_admin_user_registration_path
  .container
  %span.notice=notice
  %span.alert=alert
  %br
  %br
  =yield
  %br

app/views/tickets/_replies.html.haml
%hr
Replies:
%hr
%table
-@ticket.replies.each do |reply|
  %tr
    %td
      #{I18n.t 'strings.reply_author_label'}: #{reply.admin_user.email}
      %br
      #{I18n.t 'strings.reply_created_label'}: |
      #{reply.created_at.localtime.strftime('%F %R')}
      %br
      #{I18n.t 'strings.reply_body_label'}: #{reply.body}
      %br
      %br

app/views/tickets/_ticket.html.haml
.ticket
  %br
  %br
  %table
    %tr
      %td
        #{I18n.t 'strings.ticket_name_label'}:
      %td
        =@ticket.name
    %tr
      %td
        #{I18n.t 'strings.ticket_email_label'}:
      %td
        =@ticket.email
    %tr
      %td
        #{I18n.t 'strings.ticket_department_label'}:
      %td
        =@ticket.code
    %tr
      %td
        #{I18n.t 'strings.ticket_subject_label'}:
      %td
        =@ticket.subject
    %tr
      %td
        #{I18n.t 'strings.ticket_description_label'}:
      %td
        =@ticket.description
    %tr
      %td
        #{I18n.t 'strings.ticket_department_label'}:
      %td
        =@ticket.department
    %tr
      %td
        #{I18n.t 'strings.ticket_status_label'}:
      %td
        =@ticket.status.name

app/views/tickets/new.html.haml
.ticket
  =semantic_form_for @ticket do |f|
    =f.inputs :name
    =f.inputs :email
    =f.inputs :subject
    =f.inputs :description
    =f.inputs :department
    =f.actions

app/views/tickets/show.html.haml
=link_to 'Edit ticket', edit_ticket_path(@ticket)
=render 'ticket'
=render 'replies'